# Practice scripts from Oreilly session

In [2]:
import numpy as np

In [16]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print("Numpy Array:", arr)
print("Array Shape:", arr.shape)
print("Array Data Type:", arr.dtype)
print("items form index 1 to 3:", arr[1:4])

Numpy Array: [1 2 3 4 5]
Array Shape: (5,)
Array Data Type: int32
items form index 1 to 3: [2 3 4]


In [17]:
print(np.ones((3, 4)))
print(np.zeros((2, 5)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
print(np.ones(10))
print(np.ones(10) / 2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


In [13]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Linear space between 0 and 1 with 5 values
np.linspace(0, 1, 5) 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
num_list = [1, 2, 3, 4, 5]
# Do it in traditional way, list comprehension and map function
print([x * 2 for x in num_list])
print(list(map(lambda x: x * 2, num_list)))

# Using numpy array for vectorized operations
num_array = np.array(num_list)
print(num_array * 2)
print(num_array > 2)

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]
[ 2  4  6  8 10]
[False False  True  True  True]


In [28]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print(arr[True, False, True, False, True])
print(arr[arr > 2])
print(arr[arr % 2 == 0])


[]
[3 4 5]
[2 4]
