### Scribbling Pad

In [5]:
import numpy as np

np.ones(4, dtype=int)


array([1, 1, 1, 1])

In [7]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])