# NumPy
---
NumPy (Numerical Python) is a library that adds support for large, multi-dimensional arrays and matrices, along with a wide range of high-performance mathematical functions to operate on them. This makes it an essential tool for Python developers working with numerical data.

**Key Benefits of NumPy:**

* Speed: NumPy arrays are much faster than Python lists for numerical computations.
* Efficient Memory Use: NumPy arrays store data in a compact, contiguous block of memory, reducing memory usage and improving cache performance.
* Vectorized Operations: NumPy allows you to perform operations on entire arrays at once, eliminating the need for loops and making your code more concise and readable.

##### First, import the NumPy library

In [2]:
import numpy as np

**Creating Arrays**

In [9]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
np.array([(1,2,3),(4,5,6)], dtype = int)

array([[1, 2, 3],
       [4, 5, 6]])

**Creating Arrays with placeholders**

In [13]:
ones = np.zeros((3,3))
zeros = np.ones((3,3))
sevens = np.full((3,3), 7)

print(ones)
print(zeros)
print(sevens)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


**Inpecting the Arrays**

In [20]:
a = np.eye(5, dtype=int)

print(a)
print(a.shape)
print(len(a))
print(a.ndim)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
(5, 5)
5
2
